### ISSUE TITLE
是否考虑更新支持到“鲲鹏”机器人框架？

### ISSUE THREAD

**Issue by phoenixxie0** [0honus0/efb-wechat-cutecat-slave#28]
是否考虑更新支持到“鲲鹏”机器人框架？我看了一下，该框架支持新版本微信，可以实现自动登录了。用现在的slave版本，配合ihttp的鲲鹏版本插件，可以实现基本功能，如发送接收消息，但是好友列表之类的有点问题。

**Comment by 0honus0** [comment]
好像是刚出来的框架，等一段时间看看吧。现在还有开源的那个项目没试，后继看稳定性和功能来选一个作为新的微信后端吧

**Comment by phoenixxie0** [comment]
可爱猫更新到5.2.9了，支持到weixin 3.4了，还行，但是问题是ihttp插件有问题，1.1.6版本的无法支持，1.1.7版本的无法发送图片，尴尬

**Comment by 0honus0** [comment]
去频道试一下那个不会强制更新的可爱猫+ihttp1.6试下吧

**Comment by QQ-War** [comment]
> 可爱猫更新到5.2.9了，支持到weixin 3.4了，还行，但是问题是ihttp插件有问题，1.1.6版本的无法支持，1.1.7版本的无法发送图片，尴尬

ihttp插件需要下载e语言编译环境来检查，太麻烦了。

**Comment by phoenixxie0** [comment]
> > 可爱猫更新到5.2.9了，支持到weixin 3.4了，还行，但是问题是ihttp插件有问题，1.1.6版本的无法支持，1.1.7版本的无法发送图片，尴尬
> 
> ihttp插件需要下载e语言编译环境来检查，太麻烦了。

e语言编译环境好像挺简单的，gitee上有需要的模块，弄个吾爱pj版本的e语言环境就行了

**Comment by phoenixxie0** [comment]
可爱猫5.5.4   iHTTP插件在收到获取好友列表的时候，返回的数据里，好友备注不再是remark。而是note。导致python端出现错误，无法获取到正确的好友列表 
`
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/efb_wechat_cutecat_slave/__init__.py", line 444, in poll
    self.cron_update_task(cron_timer)
  File "/usr/local/lib/python3.8/dist-packages/efb_wechat_cutecat_slave/__init__.py", line 347, in cron_update_task
    self.update_friend_info()
  File "/usr/local/lib/python3.8/dist-packages/efb_wechat_cutecat_slave/__init__.py", line 466, in update_friend_info
    return self.process_friend_info() + self.process_group_info()
  File "/usr/local/lib/python3.8/dist-packages/efb_wechat_cutecat_slave/__init__.py", line 507, in process_friend_info
    remark = friend['remark']
KeyError: 'remark'
`

**Comment by 0honus0** [comment]
暂时还未考虑适配新版插件
